// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp8WN6ebfCdZsrNPc2Q5ya-dG_40MyLns',
    appId: '1:477075926298:web:3920dd00bfcef69c9050a3',
    messagingSenderId: '477075926298',
    projectId: 'chatapptute-96024',
    authDomain: 'chatapptute-96024.firebaseapp.com',
    storageBucket: 'chatapptute-96024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApfbHcdiwLor960I4fPLISewWIBcWsDws',
    appId: '1:477075926298:android:df9e21e10f9598ef9050a3',
    messagingSenderId: '477075926298',
    projectId: 'chatapptute-96024',
    storageBucket: 'chatapptute-96024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl6cDC0ujekfreI-sVo66Qv3YL_U-40AE',
    appId: '1:477075926298:ios:b7d0995a55fc61b99050a3',
    messagingSenderId: '477075926298',
    projectId: 'chatapptute-96024',
    storageBucket: 'chatapptute-96024.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl6cDC0ujekfreI-sVo66Qv3YL_U-40AE',
    appId: '1:477075926298:ios:b7d0995a55fc61b99050a3',
    messagingSenderId: '477075926298',
    projectId: 'chatapptute-96024',
    storageBucket: 'chatapptute-96024.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp8WN6ebfCdZsrNPc2Q5ya-dG_40MyLns',
    appId: '1:477075926298:web:e769b5bbaf25e9019050a3',
    messagingSenderId: '477075926298',
    projectId: 'chatapptute-96024',
    authDomain: 'chatapptute-96024.firebaseapp.com',
    storageBucket: 'chatapptute-96024.appspot.com',
  );
}
